name: 'Diff Pages Action'
author: 'Sungwon Lee'
description: 'Take screenshots of updated static web pages'
inputs:
  base-path:
    description: 'Path to base static pages.'
    required: true
  head-path:
    description: 'Path to head static pages.'
    required: true
  pattern:
    description: 'glob pattern for detecting page files.'
    required: true
    default: '**/*.+(htm|html)'
  port:
    description: 'Port for running local static web server'
    required: true
    default: 8000
  output-path:
    description: 'Path for saving final screenshots.'
    required: true
    default: diff-pages-action/output
  temp-path:
    description: 'Path for saving temporary screenshots.'
    required: true
    default: diff-pages-action/tmp
outputs:
  path:
    description: 'Path to saved screenshots.'
runs:
  using: 'docker'
  image: 'Dockerfile'